var glyphList = {};

glyphList["gain"] = "01000010000";
glyphList["old"] = "01010010000";
glyphList["past"] = "01010010100";
glyphList["destroy"] = "01010101010";
glyphList["breathe"] = "01111100000";
glyphList["defend"] = "01100011001";
glyphList["help"] = "01010111000";
glyphList["pursue"] = "11011000000";
glyphList["weak"] = "01011001000";
glyphList["avoid"] = "11101001000";
glyphList["rebel"] = "01101010010";
glyphList["seperate"] = "01011111010";
glyphList["forget"] = "00000010100";
glyphList["create"] = "00101110100";
glyphList["advanced"] = "10010000100";
glyphList["distance"] = "11000000100";
glyphList["courage"] = "00010011100";
glyphList["want"] = "00000011101";
glyphList["stay"] = "00000011110";
glyphList["shapers"] = "10011011110";
glyphList["chaos"] = "11101110101";
glyphList["liberate"] = "10111100100";
glyphList["present"] = "00011011000";
glyphList["inside"] = "00011001000";
glyphList["answer"] = "00011101000";
glyphList["hide"] = "00111011000";
glyphList["simple"] = "00000011000";
glyphList["more"] = "00000111000";
glyphList["save"] = "00100111000";
glyphList["question"] = "10011010000";
glyphList["escape"] = "10111010000";
glyphList["clear"] = "10000100001";
glyphList["contemplate"] = "10111110011";
glyphList["use"] = "00100101000";
glyphList["search"] = "00011111000";
glyphList["easy"] = "00001110001";
glyphList["react"] = "00011101010";
glyphList["capture"] = "00100111101";
glyphList["lose"] = "00100001000";
glyphList["pure"] = "10001101000";
glyphList["imperfect"] = "00111110000";
glyphList["human"] = "00011011001";
glyphList["recharge"] = "11010100000";
glyphList["closeall"] = "11100100111";
glyphList["strong"] = "00011011000";
glyphList["xm"] = "00011111000";
glyphList["portal"] = "01111011110";

puzzleList = [];
puzzleList.push(["gain","truth","open","human","soul"]);
puzzleList.push(["old","nature","less","strong","now"]);
puzzleList.push(["past","chaos","create","future","peace"]);
puzzleList.push(["past","path","create","future","journey"]);
puzzleList.push(["destroy","lie","inside","gain","soul"]);
puzzleList.push(["destroy","civilization","end","conflict","war"]);
puzzleList.push(["breathe","inside","xm","lose","self"]);
puzzleList.push(["defend","destiny","defend","human","civilization"]);
puzzleList.push(["defend","human","civilization","xm","message"]);
puzzleList.push(["defend","human","civilization","shapers","lie"]);
puzzleList.push(["defend","human","civilization","portal","data"]);
puzzleList.push(["defend","human","civilization","shapers","portal"]);
puzzleList.push(["help","enlightenment","capture","all","portal"]);
puzzleList.push(["help","resistance","capture","all","portal"]);
puzzleList.push(["help","human","civilization","pursue","destiny"]);
puzzleList.push(["pursue","path","outside","shapers","lie"]);
puzzleList.push(["pursue","conflict","war","advance","chaos"]);
puzzleList.push(["weak","human","destiny","destroy","civilization"]);
puzzleList.push(["avoid","chaos","repair","potential","war"]);
puzzleList.push(["avoid","perfection","stay","human","self"]);
puzzleList.push(["avoid","chaos","avoid","shapers","lie"]);
puzzleList.push(["rebel","thought","evolution","destiny","now"]);
puzzleList.push(["separate","mind","body","discover","enlightenment"]);
puzzleList.push(["separate","truth","lie","shapers","future"]);
puzzleList.push(["forget","past","see","present","danger"]);
puzzleList.push(["forget","war","see","distance","peace"]);
puzzleList.push(["create","pure","future","not","war"]);
puzzleList.push(["create","pure","future","human","civilization"]);
puzzleList.push(["create","separate","path","end","journey"]);
puzzleList.push(["advance","civilization","pursue","shapers","path"]);
puzzleList.push(["distance","self","avoid","human","lie"]);
puzzleList.push(["courage","attack","shapers","portal","together"]);
puzzleList.push(["want","truth","pursue","difficult","path"]);
puzzleList.push(["stay","strong","together","defend","resistance"]);
puzzleList.push(["shapers","portal","data","create","chaos"]);
puzzleList.push(["shapers","portal","message","destroy","civilization"]);
puzzleList.push(["shapers","want","human","mind","future"]);
puzzleList.push(["shapers","lead","human","complex","journey"]);
puzzleList.push(["chaos","war","conflict","discover","peace"]);
puzzleList.push(["liberate","portal","liberate","human","mind"]);
puzzleList.push(["present","chaos","create","future","civilization"]);
puzzleList.push(["inside","mind","inside","soul","peath"]);
puzzleList.push(["answer","question","discover","difficult","truth"]);
puzzleList.push(["hide","resistance","advance","strong","together"]);
puzzleList.push(["simple","truth","shapers","destroy","civilization"]);
puzzleList.push(["simple","old","truth","journey","inside"]);
puzzleList.push(["more","data","gain","portal","advance"]);
puzzleList.push(["save","human","civilization","destroy","portal"]);
puzzleList.push(["question","less","forget","all","lie"]);
puzzleList.push(["escape","body","journey","outside","present"]);
puzzleList.push(["escape","body","mind","self","want"]);
puzzleList.push(["clear","mind","liberate","barrier","body"]);
puzzleList.push(["contemplate","future","not","shapers","path"]);
puzzleList.push(["contemplate","restraint","discover","more","courage"]);
puzzleList.push(["use","restraint","follow","easy","path"]);
puzzleList.push(["use","mind","use","courage","change"]);
puzzleList.push(["search","destiny","create","pure","future"]);
puzzleList.push(["easy","path","future","follow","shapers"]);
puzzleList.push(["react","rebel","question","shapers","lie"]);
puzzleList.push(["capture","portal","defend","portal","courage"]);
puzzleList.push(["lose","shapers","message","gain","chaos"]);
puzzleList.push(["pure","human","failure","now","chaos"]);
puzzleList.push(["imperfect","xm","message","human","chaos"]);
puzzleList.push(["imperfect","truth","accept","complex","answer"]);
puzzleList.push(["human","shapers","together","create","destiny"]);
puzzleList.push(["human","not","together","civilization","deteriorate"]);
puzzleList.push(["repair","present","repair","human","soul"]);
puzzleList.push(["repair","soul","less","human","harm"]);
puzzleList.push(["closeall","thought","past","present","future"]);
puzzleList.push(["strong","together","war","together","destiny"]);
puzzleList.push(["strong","together","war","together","chaos"]);
puzzleList.push(["xm","path","future","destiny","peace"]);
puzzleList.push(["xm","create","complex","human","destiny"]);
puzzleList.push(["portal","create","danger","pursue","safety"]);
puzzleList.push(["portal","potential","help","human","future"]);
puzzleList.push(["portal","barrier","defend","human","shapers"]);
puzzleList.push(["portal","improve","human","future","civilization"]);
